authentication/environment.go
Moving this up from [the Azure Stack Provider](https://github.com/terraform-providers/terraform-provider-azurestack/blob/master/azurestack/config.go#L145-L148) and adding some validation logic so that we can reuse it in the AzureRM Backend in the future
=> Support for loading the environment from the specified endpoint

authentication/builder.go, authentication/config.go
This exists since this information will be used by Azure Stack.
It's intentionally /not/ scoped to that project since it's required in the Backend too
=> Adding support for a custom endpoint for Resource Manager

storage/sas_token.go, storage/sas_token_test.go
Splitting this out from the AzureRM Repository, since it's needed in the Azure Backend
=> Splitting out the SAS Token Generation

authentication/auth_method_azure_cli_parsing.go, authentication/auth_method_azure_cli_parsing_test.go, authentication/azure_cli_access_token.go, authentication/azure_cli_access_token_test.go, authentication/azure_cli_profile.go, authentication/azure_cli_profile_population.go, authentication/builder.go
Apparently [at some point CloudShell switched to using MSI](https://github.com/hashicorp/go-azure-helpers/pull/10#issuecomment-441281892) for authenticating which means this code is no longer needed.
This is technically a breaking change, so I guess we'll release this and #9 as 0.2.0
=> Removing CloudShell

authentication/auth_method_azure_cli_parsing.go, authentication/auth_method_azure_cli_token.go, authentication/auth_method_azure_cli_token_test.go, authentication/azure_cli_access_token.go, authentication/azure_cli_access_token_test.go, authentication/azure_cli_profile.go, authentication/azure_cli_profile_population.go, authentication/builder.go
This PR introduces a new authentication method: authenticating using the Azure CLI by obtaining an Access Token.
The intention is that this'd replace the existing Azure CLI Parsing authentication method, such that we now delegate to the Azure CLI to obtain the token. ~Once this PR's merged I think it'd be sensible to split CloudShell out into it's own auth method, so that we can remove the older Azure CLI Parsing authentication method in the future.~ CloudShell's using MSI - so I guess we can just outright remove the Azure CLI Parsing functionality once this is merged
Since we're not relying on retrieving the Access Token, this fixes https://github.com/terraform-providers/terraform-provider-azurerm/pull/1752 and fixes #4
=> New Auth Method: Azure CLI Tokens

sender/sender.go
So that it's possible to reuse it, since it's the same in both. This allows us to both support Proxies and filtering the request logs in Azure Stack
=> Pulling the sender out from AzureRM

storage/sas_token.go, storage/sas_token_test.go
fix for [azure #2465](https://github.com/terraform-providers/terraform-provider-azurerm/issues/2465) panic:
```
2018-12-06T18:45:56.774+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: panic: runtime error: index out of range
2018-12-06T18:45:56.774+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: 
2018-12-06T18:45:56.774+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: goroutine 87 [running]:
2018-12-06T18:45:56.774+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: github.com/terraform-providers/terraform-provider-azurerm/azurerm.parseAzureStorageAccountConnectionString(0xc000390a00, 0x45, 0x8, 0x4, 0xc0009abde8)
2018-12-06T18:45:56.774+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: …
```
=> prevent panic in ParseAccountSASConnectionString

authentication/azure_cli_access_token.go, authentication/azure_cli_access_token_test.go, authentication/azure_cli_profile_population.go
since we no longer require valid tokens (since we always request one) - we can also clean up this code path too
=> refactor: removing unused code leftover from the azure cli parsing auth

authentication/auth_method_azure_cli_token.go
Currently when the user is trying to use Azure CLI authentication, but isn't logged in they get this error:
```
* provider.azurerm: Error building AzureRM Client: No Subscription was Marked as Default in the Azure Profile.
```
This PR wraps this error telling the user to login:
```
* provider.azurerm: Error building AzureRM Client: Error retrieving the Profile from the Azure CLI: No Subscription was Marked as Default in the Azure Profile. Please re-authenticate using `az login`.
```
=> Wrapping the azure cli error for a more helpful error

resourceproviders/registration.go
The check for registering resource provider will always pass since the `err` will always be `nil`.
=> Wrong error object being evaluated in nil check

authentication/auth_method.go, authentication/auth_method_azure_cli_token.go, authentication/auth_method_client_cert.go, authentication/auth_method_client_secret.go, authentication/auth_method_msi.go, authentication/config.go
This allows the same sender to be sent for both the Auth requests and Client requests; which should ensure the proxy configuration is the same
=> passing the sender to the request method

resourceproviders/registration.go
This PR is created to address the regression issue after upgrading to `v0.4.0` recently:
https://github.com/terraform-providers/terraform-provider-azurerm/issues/3312
Before making this change, if you ran any acceptance test like `TestAccAzureRMResourceGroup_basic`, you will see below error:
```
Error: Error ensuring Resource Providers are registered: Cannot register provider Microsoft.Cdn 
with Azure Resource Manager: resources.ProvidersClient#Register: Failure responding to request:
StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 
Code="InvalidResourceNamespace" Message="The resource namespace 'Microsoft.Cdn' is invalid.".
```
With this change, the test can pass.
=> Fix the code logic to generate the required provider list.

authentication/auth_method_azure_cli_token.go, authentication/azure_cli_profile.go, authentication/builder.go
Unfortunately when authenticating as a Service Principal not all required information is available
As such instead we support authenticating as a Service Principal using the separate auth methods
for Client Certificate/Secret authentication.
The intention of this is to give more a more helpful error when you're authenticated as a Service Principal using the Azure CLI
```
$ go test -v ./authentication/
=== RUN   TestAzureCLITokenAuth_isApplicable
--- PASS: TestAzureCLITokenAuth_isApplicable (0.00s)
=== RUN   TestAzureCLITokenAuth_populateConfig
--- PASS: TestAzureCLITokenAuth_populateConfig (0.00s)
=== RUN   TestAzureCLITokenAuth_validate
--- PASS: TestAzureCLITokenAuth_validate (0.00s)
=== RUN   TestServicePrincipalClientCertAuth_builder
--- PASS: …
```
=> azure cli: verifying we're authenticated as a User

storage/sas_token.go, storage/sas_token_test.go
Hey,
i need this functionality in order to create SAS tokens for blob containers in at least two use cases:
- `azurerm_analysis_services_server`: backup blob container + sas
- `azurerm_data_factory_integration_runtime_managed`: custom setup script container + sas
I'm going to implement a data provider for this token. It is similar to the storage account SAS token but does not exist yet.
=> Add function to compute SAS token for blob container

authentication/auth_method.go, authentication/auth_method_azure_cli_token.go, authentication/auth_method_client_cert.go, authentication/auth_method_client_secret.go, authentication/auth_method_client_secret_multi_tenant.go, authentication/auth_method_msi.go, authentication/config.go
This PR does a couple of things necessary to be able to use the Key Vault and Storage Authorizers within the Azure Providers:
1. Exposes both the Primary and Multi Tenant authorizers to be able to return an Authorizer for the Primary Tenant
2. .. via the new method `BearerAuthorizerCallback` which can be used to obtain a BearerAuthorizerCallback for the Primary Tenant - which in turn can be used for the Key Vault and Storage Authorizers which require using the Primary Tenant
There's a couple of renames in here too:
1. Renaming the struct `MultiOAuth` struct to `AuthConfig`
2. Renaming the func `GetMultiOAuthConfig` to `BuildOAuthConfig`, since it's building the OAuth Configuration
Tests pass:
```
$ make test
go mod download
warning: pattern "all" matched no module dependencies
go vet …
```
=> Auth: exposing the Primary and Multi Tenant Authorizers

storage/sas_token.go, storage/sas_token_test.go
Required for [this](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1868) issue.
Adds helper methods to return the sas connection string and the connection strings specific to one of the account type: blob, file, queue, table.
I am preparing another PR in [terraform-provider-azurerm](https://github.com/terraform-providers/terraform-provider-azurerm) to integrate this change and fix the above issue.
=> add possibility to return connection string outputs from storage sas

authentication/auth_method_azure_cli_token.go
Do not simply return when stderr is not empty, since az cli might output warning to stderr. Instead, checking the returned `err` of `cmd.Wait()` is enough to tell whether the command exited with status code 0 or not.
This fixes: terraform-providers/terraform-provider-azurerm#8358
=> cli auth result depends on exit code

authentication/auth_method_azure_cli_token.go, authentication/azure_cli_access_token.go, authentication/azure_cli_access_token_test.go
The `err` only contains information like: "exit status: 1", which do not provide helpful information when trouble shooting.
=> adding detailed error when az command failed

authentication/auth_method_azure_cli_token.go, authentication/auth_method_azure_cli_token_test.go, authentication/auth_method_client_cert.go, authentication/auth_method_client_cert_test.go, authentication/auth_method_client_secret.go, authentication/auth_method_client_secret_multi_tenant.go, authentication/auth_method_client_secret_multi_tenant_test.go, authentication/auth_method_client_secret_test.go, authentication/builder.go
Support tenant-only configurations with or without associated subscription(s)
See testing matrix at https://docs.google.com/spreadsheets/d/1HXJrTLPloqsIaZNnv4ynhyy_9X5ibbW4BAG9zr0oCrE
* Add a new Builder field `TenantOnly`.
* When true for CLI authentication, locates a suitable CLI 'account' by tenant ID instead of by subscription ID, and `SubscriptionID` is ignored / not required.
* Works with or without the `--allow-no-subscriptions` argument to `az login`.
* Will now support versions of Azure CLI that do or don't populate tenant-level accounts where a linked subscription is found.
* For all auth methods, permits validation without specifying `SubscriptionID`.
* Allows use of modules that don't operate on subscriptions (e.g. graphrbac).
- …
=> Support configuring a Tenant ID and ignoring subscriptions

authentication/auth_method_azure_cli_token.go, authentication/auth_method_azure_cli_token_multi_tenant.go, go.mod, go.sum
Note
- The `-t` argument to `az account get-access-token` is "preview-only"
but is included in recent releases of azure-cli by default
- Also includes a version check for Azure CLI, returning a detailed error if the available version is too old
Tested on a fresh azure-cli v2.14.0 installation on a new debian VM, with these scenarios: https://docs.google.com/spreadsheets/d/1HXJrTLPloqsIaZNnv4ynhyy_9X5ibbW4BAG9zr0oCrE/edit#gid=0
=> Select the correct access token in a multi tenant scenario and subscription ID is not specified

polling/poller.go, resourcemanager/resourceids/ids.go
Ultimately this enables us to consolidate this into a single place - this also introduces a `NewLongRunningPollerFromResponse` for the Poller
=> upstreaming: moving Resource ID parsing into this package

formatting/dates.go
This allows us to contain this within a single place, since this is necessary in multiple downstream dependencies.
=> formatting: introducing a package for parsing dates in a given format

polling/poller.go
Necessary to replicate this behaviour:
https://github.com/terraform-providers/terraform-provider-azurerm/blob/0a29f734f5406e4772c65b871df5ef871454ab81/azurerm/internal/services/eventhub/eventhub_cluster_resource.go#L173-L176
Since right now we don't have access to the Future's HTTP Response when this fails:
https://github.com/terraform-providers/terraform-provider-azurerm/blob/b2fb4064d30a91fd819e0552cff2cad98205ee08/azurerm/internal/services/eventhub/eventhub_cluster_resource.go#L165-L169
=> polling: exposing the latest http response from the future

sender/sender.go
When fixing track2 error https://github.com/Azure/azure-sdk-for-go/issues/14729 , we find that sometimes the response returns nil, but the error is not nil.
=> Update logging for possible artificial response error 

resourcemanager/resourceids/interface.go, resourcemanager/resourceids/old.go, resourcemanager/resourceids/parse.go, resourcemanager/resourceids/parse_test.go
This allows the parsing of Resource ID's which contain Scopes either at the start or the end - but not in the middle (since we've not seen any) - as such this should be fine.
This means that Resource ID's now need to expose a slice of expected segments, for example:
```go
func (id ConfigurationStoreId) ID() string {
fmtString := "/subscriptions/%s/resourceGroups/%s/providers/Microsoft.AppConfiguration/configurationStores/%s"
return fmt.Sprintf(fmtString, id.SubscriptionId, id.ResourceGroupName, id.ConfigStoreName)
}
func (id ConfigurationStoreId) Segments() []resourceids.Segment {
return []resourceids.Segments{
resourceids.StaticSegment("subscriptions", "subscriptions", "exampleValue"),
resourceids.SubscriptionIdSegment("subscriptionId", "exampleValue"), …
```
=> resourcemanager: introducing an updated Resource ID Parser based on Segments

resourcemanager/resourceids/parse.go, resourcemanager/resourceids/parse_test.go
This PR introduces a check at the end of the Resource ID parsing to ensure that all of the required segments have a value, which fixes an issue where the last segment could be empty and pass validation
=> resourcemanager/resourceids: raising an error if any segments are empty

resourcemanager/tags/expand.go, resourcemanager/tags/flatten.go
This enables this to be used directly in Read functions rather than having an intermediate translation function.
=> resourcemanager/tags: Flatten now returns map[string]interface{}

resourcemanager/commonschema/identity_system.go, resourcemanager/commonschema/identity_system_or_user.go, resourcemanager/commonschema/identity_system_user.go, resourcemanager/commonschema/identity_user.go
We need to support where Identity is both Required, Optional and Computed - however whilst doing so I realised that adding a `{Name}Required` function would differ from the schema used in Resource Groups and Location where the Required method is the default, so this PR refactors the identity function to take this into account.
=> identity: refactoring to be Required, Optional and Computed

resourcemanager/identity/constants.go, resourcemanager/identity/system_and_user_assigned_list.go, resourcemanager/identity/system_and_user_assigned_map.go, resourcemanager/identity/system_assigned.go, resourcemanager/identity/system_or_user_assigned_list.go, resourcemanager/identity/system_or_user_assigned_map.go, resourcemanager/identity/user_assigned_list.go, resourcemanager/identity/user_assigned_map.go
This works around an issue where the API specifies one case but returns another, such as in https://github.com/Azure/azure-rest-api-specs/issues/12330 - as such these should be parsed insensitively when coming back from the API
=> resourcemanager/identity: normalizing the casing of the `type`

resourcemanager/commonschema/edge_zone.go, resourcemanager/edgezones/normalize.go, resourcemanager/edgezones/normalize_test.go, resourcemanager/edgezones/schema.go
These are intended to be used as `edge_zone = commonschema.EdgeZoneOptional()`
At this time we intentionally only support Optional, OptionalForceNew and Computed as these are the use-cases - however we may expand this to support Required in future.
Supersedes #97
=> resourcemanager/commonschema: adding support for Edge Zones

authentication/config.go
Ensure that tokens returned via Azure CLI or MSI authentication will still work for data plane APIs, because those both return legacy ADAL tokens.
=> Bugfix: add compatiblity for ADAL tokens in auth.Config.MSALBearerAuthorizerCallback()

resourcemanager/identity/constants.go, resourcemanager/identity/legacy_system_and_user_assigned_list.go, resourcemanager/identity/legacy_system_and_user_assigned_list_test.go, resourcemanager/identity/legacy_system_and_user_assigned_map.go, resourcemanager/identity/legacy_system_and_user_assigned_map_test.go
This ensures the UX is consistent insofar as the legacy value `SystemAssigned,UserAssigned` becomes consistent
as `SystemAssigned, UserAssigned`
=> resourcemanager/identity: introducing a struct/expand/flatten functions for the V3 (Legacy) Identity Types

resourcemanager/systemdata/model.go
This is a simple read only structure. It does not specify a custom unmarshal function, and the marshal function will always return an empty string.
This PR adds functionality requited by https://github.com/hashicorp/pandora/pull/808
=> Add SystemData struct.

authentication/auth_method_azure_cli_token.go, authentication/auth_method_azure_cli_token_multi_tenant.go, authentication/azure_cli_profile_multi_tenant.go
Since v2.37.0, CLI migrates to using MS graph for the AD related apis,
this causes breaking change on the resulting data model, which includes
feild `object_id` being renamed to `id`. This causes CLI auth method
failed to work for CLI since v2.37.0.
This commit checks the CLI version and read the corresponding field for
object id differently, for both CLI and multi tenant CLI auth methods.
Besides, the multi tenant CLI auth method seems to be broken even prior
to v2.37.0, when there is nothing configured in the provider block. This
commit also fixed that part by populating the tenant id and subscription
id in case they are empty.
Fix #118
=> Auth: CLI method mitigate breaking change introduced in CLI v2.37.0

go.sum, resourcemanager/identity/system_and_user_assigned_list.go, resourcemanager/identity/system_and_user_assigned_map.go, resourcemanager/identity/system_assigned.go, resourcemanager/identity/system_or_user_assigned_list.go, resourcemanager/identity/system_or_user_assigned_map.go, resourcemanager/identity/tfschema_model.go, resourcemanager/identity/user_assigned_list.go, resourcemanager/identity/user_assigned_map.go
The identity package currently has support for expanding/flattening from/to the raw representation of identity (i.e. `[]interface{}`), to/from the SDK types (e.g. `SystemAndUserAssignedList`). This works fine for the untyped flavor code. However, it lacks of supports for the code using typed SDK.
This PR defines models to be used for the typed SDK:
- `ModelUserAssinged`: for user assigned identity (either the user assigned identity in the SDK definition is a list or a map)
- `ModeSystemAssigned`: for system assigned identity
- `ModeSystemAssignedUserAssigned`: for system and/or user assigned identity, it doesn't matter whether it is "or" or "and" for the schema model (thought it matters when choosing the correct schema and the correct expand/flatten function).
Arguably, the `tfschema` …
=> Identity: Add expand/flatten from/to the typed schema model

lang/response/response.go, lang/response/response_test.go
This allows custom status codes to be checked as required to workaround Swagger/API issues whilst also handling the response being nil due to a dropped connection or similar.
=> lang/response: making WasNotFound public

authentication/environment.go
Support a default environment when a single env is returned from the metadata service, and no environment name was specified
=> Support a default environment from metadata

resourcemanager/commonids/provisioning_service.go, resourcemanager/commonids/provisioning_service_test.go
works around inconsistency in source data for deviceprovisioningservices
=> CommonIds: add a commonid for `ProvisioningServiceId`

authentication/auth_method_oidc.go, authentication/auth_method_oidc_test.go, authentication/builder.go
Adds the ability to specify a path to an OIDC token in place of supplying the contents of the token.
=> Add ability to specify path to OIDC token

resourcemanager/commonids/cloud_services_ip_configuration.go, resourcemanager/commonids/cloud_services_ip_configuration_test.go, resourcemanager/commonids/cloud_services_public_ip.go, resourcemanager/commonids/cloud_services_public_ip_test.go, resourcemanager/commonids/express_route_circuit_peering.go, resourcemanager/commonids/express_route_circuit_peering_test.go, resourcemanager/commonids/network_interface.go, resourcemanager/commonids/network_interface_ip_configuration.go, resourcemanager/commonids/network_interface_ip_configuration_test.go, resourcemanager/commonids/network_interface_test.go, resourcemanager/commonids/public_ip_address.go, resourcemanager/commonids/public_ip_address_test.go, resourcemanager/commonids/virtual_hub_bgp_connection.go, resourcemanager/commonids/virtual_hub_bgp_connection_test.go, resourcemanager/commonids/virtual_hub_ip_configuration.go, resourcemanager/commonids/virtual_hub_ip_configuration_test.go, resourcemanager/commonids/virtual_machine_scale_set_ip_configuration.go, resourcemanager/commonids/virtual_machine_scale_set_ip_configuration_test.go, resourcemanager/commonids/virtual_machine_scale_set_network_interface.go, resourcemanager/commonids/virtual_machine_scale_set_network_interface_test.go, resourcemanager/commonids/virtual_machine_scale_set_public_ip_address.go, resourcemanager/commonids/virtual_machine_scale_set_public_ip_address_test.go, resourcemanager/commonids/virtual_router_peering.go, resourcemanager/commonids/virtual_router_peering_test.go, resourcemanager/commonids/virtual_wan_p2s_vpn_gateway.go, resourcemanager/commonids/vpn_connection.go, resourcemanager/commonids/vpn_connection_test.go
These should be `resourceGroupName` rather than `resourceGroup`
=> refactor: resourceGroup -> resourceGroupName for consistency

resourcemanager/zones/expand.go, resourcemanager/zones/flatten.go
These allow the `.Expand` and `.Flatten` functions to become Typed by default
=> resourcemanager/zones: adding the Untyped Expand/Flatten functions

resourcemanager/commonids/user_assigned_identity.go, resourcemanager/commonids/user_assigned_identity_test.go
Matching the behaviour introduced in https://github.com/hashicorp/pandora/pull/2011 which unblocks fixing https://github.com/hashicorp/pandora/actions/runs/4073772510
=> resourcemanager/commonids: refactoring User Assigned Identity ID to use the updated segment name

storage/sas_token.go, storage/sas_token_test.go
This is related to https://github.com/hashicorp/terraform-provider-azurerm/issues/17558, https://github.com/hashicorp/terraform-provider-azurerm/issues/18807
See https://docs.microsoft.com/en-us/rest/api/storageservices/create-account-sas#construct-the-signature-string for reference.
=> Storage Account SAS: The format is changed if signed version >= 2020-12-06

resourcemanager/commonids/subnet.go, resourcemanager/commonids/subnet_test.go, resourcemanager/commonids/virtual_network.go, resourcemanager/commonids/virtual_network_test.go
=> commonids: add common ids for `SubnetId` and `VirtualNetworkId`

eventhub/sas_token.go, eventhub/sas_token_test.go
To figure out https://github.com/hashicorp/terraform-provider-azurerm/issues/7160, it has to submit this PR to add Event Hub SAS Helper first. After this is merged, it has to submit another PR to add Event Hub SAS data source in terraform azurerm provider.
--- PASS: TestComputeEventHubSASConnectionUrl (0.00s)
--- PASS: TestComputeEventHubSASConnectionString (0.00s)
--- PASS: TestComputeEventHubSASToken (0.00s)
--- PASS: TestParseEventHubConnectionString (0.00s)
Reference:
https://docs.microsoft.com/en-us/rest/api/eventhub/generate-sas-token#powershell
https://docs.microsoft.com/en-us/azure/event-hubs/authenticate-shared-access-signature#generate-a-shared-access-signature-token
=> Add support for Event Hub SAS Helper

resourcemanager/commonids/storage_account.go, resourcemanager/commonids/storage_account_test.go, resourcemanager/commonids/storage_container.go, resourcemanager/commonids/storage_container_test.go
This PR introduces 2 new Common IDs for Storage Account and Storage Container - whilst I've considered including File, Queue and Table into this list - those aren't really used outside the `storage` package, so there's less value in moving those here.
=> `resourcemanager/commonids`: Common IDs for Storage Account & Storage Container

resourcemanager/commonids/app_service.go, resourcemanager/commonids/app_service_environment.go, resourcemanager/commonids/app_service_environment_test.go, resourcemanager/commonids/app_service_function_app.go, resourcemanager/commonids/app_service_plan.go, resourcemanager/commonids/app_service_plan_test.go, resourcemanager/commonids/app_service_test.go, resourcemanager/commonids/app_service_web_app.go
This PR introduces new Common IDs for App Service, App Service Environment and App Service Plan.
This also introduces a couple of wrappers for both Function Apps and Web Apps (since these are just App Service instances today, but doing so allows us to differentiate these internally if needed). Since `hashicorp/pandora` only allows for a single instance of a Resource ID to match one Common ID, these are mostly for user-facing code - internally Pandora will output these as an App Service ID (at least for now).
=> `resourcemanager/commonids`: adding new Common IDs for App Service / App Service Environment / App Service Plan

resourcemanager/commonids/sql_database.go, resourcemanager/commonids/sql_database_test.go, resourcemanager/commonids/sql_elastic_pool.go, resourcemanager/commonids/sql_elastic_pool_test.go, resourcemanager/commonids/sql_managed_instance.go, resourcemanager/commonids/sql_managed_instance_database.go, resourcemanager/commonids/sql_managed_instance_database_test.go, resourcemanager/commonids/sql_managed_instance_test.go, resourcemanager/commonids/sql_server.go, resourcemanager/commonids/sql_server_test.go
This PR adds a new set of Common ID Types for:
1. SQL Database
2. SQL ElasticPool
3. SQL Managed Instance Database
4. SQL Managed Instance
5. SQL Server
=> Common IDs for SQL

resourcemanager/commonids/sql_database.go, resourcemanager/commonids/sql_database_test.go
Spotted this bug whilst implementing #198 / reviewing the PR on `hashicorp/terraform-provider-azurerm`
=> sql_database: updating the `Parse` method name

resourcemanager/commonids/fleet.go, resourcemanager/commonids/fleet_test.go
This PR introduces new Common IDs for Kubernetes Fleet
=> `resourcemanager/commonids`: adding new Common IDs for Kubernetes Fleet

resourcemanager/commonids/chaos_studio_capability.go, resourcemanager/commonids/chaos_studio_capability_test.go, resourcemanager/commonids/chaos_studio_target.go, resourcemanager/commonids/chaos_studio_target_test.go
Needed for partial generation of capabilities and potentially experiments (if we generate it)
=> commonids - add common IDs for chaos studio targets and capabilities

.github/workflows/automation-release.yaml
This updated the GHAs to run on regular `ubuntu-latest` agents - we're not super concerned about the speed at which this runs because releases are irregular - but this should unblock the auto release process.
=> automation: switching to use the generic agents

resourcemanager/features/user_specified_segments.go, resourcemanager/resourceids/match.go, resourcemanager/resourceids/match_test.go, resourcemanager/resourceids/parse.go
The `Match` function takes two instances of the ResourceId type and allows comparing the parsed segments for these.
Whilst this is also possible by comparing the value of `.ID()` in both instances - that's not case-aware and so will be problematic in the future - hence the need for this function which can account for case-aware comparisons.
This also exposed a feature-flag for treating User Specified Segments as case-insensitive for comparison purposes - however this isn't usable at this time and so **must not** be exposed as a toggle at this point-in-time, since it'll cause more problems than it solves. However having this internal-only feature flag allows us to built out the surrounding components ahead-of-time and add tests covering both scenarios - therefore this is beneficial to have …
=> `resourcemanager/resourceids`: adding a `Match` function

resourcemanager/identity/legacy_system_and_user_assigned_map.go, resourcemanager/identity/legacy_system_and_user_assigned_map_test.go
If the `type` of `identity` is set to `SystemAssigned, UserAssigned`(w/space), Terraform will return the following 400 error even though the `type` has not changed when updating the resource. It is caused by the [internal error](https://github.com/hashicorp/go-azure-helpers/blob/5b8e01f22f0c7713bf4660645c102916bf71bb7c/resourcemanager/identity/legacy_system_and_user_assigned_map.go#L30) (internal error: the legacy SystemAssigned,UserAssigned identity type should be being converted to the schema type - this is a bug). In this case, the type value returned from API is `SystemAssigned,UserAssigned`(no space) causing this internal error to occur. 
```
Error:
`performing CreateOrUpdate: unexpected status 400 with error: InvalidResource: The resource definition is invalid.`
```
Use the …
=> Added `UnmarshalJSON` function for `LegacySystemAndUserAssignedMap` to transform API value as required

resourcemanager/recaser/recase.go, resourcemanager/recaser/recaser_test.go, resourcemanager/recaser/registration.go
This PR 
- adds basic support for dealing with scopes in IDs (limited to potential scopes from the registered ID Types)
- adds an accessor for the registered ID Types
- adds functionality to expose errors for consumers to make decisions based on returns
- adds support for getting the id type from a resource id string for registered IDs
=> `recaser` - extend functionality and expose error handling for better utility

resourcemanager/commonschema/zone.go
As per the group discussion and consensus, this PR adds a schema for `zone` that is `Optional` and `Computed`
The result of running `make test`:
```sh
--- PASS: TestAzureEnvironmentNames (0.00s)
--- PASS: TestAccAzureEnvironmentByName (0.00s)
--- PASS: TestAccAzureEnvironmentByNameFromEndpoint (0.54s)
--- PASS: TestAccIsEnvironmentAzureStack (0.00s)
--- PASS: TestParseEventHubConnectionString (0.00s)
--- PASS: TestComputeEventHubSASToken (0.00s)
--- PASS: TestComputeEventHubSASConnectionString (0.00s)
--- PASS: TestComputeEventHubSASConnectionUrl (0.00s)
--- PASS: TestFrom_ListOfStrings (0.00s)
--- PASS: TestFrom_NilTypes (0.00s)
--- PASS: TestFrom_MapOfInterface (0.00s)
--- PASS: TestBadRequest_DroppedConnection (0.00s)
--- PASS: TestBadRequest_StatusCodes (0.00s)
--- PASS: …
```
=> Azure Zone: Add Optional Computed Schema

resourcemanager/commonschema/tags.go, resourcemanager/tags/validate.go
To support removal of the schema function in the `tags` within `terraform-provider-azurerm`
=> add commonschema and validate func for tags with max elems
