Makefile
go.mod
go.sum

This /should/ also fix the build 🙃

Support for Go Modules

---

resourceproviders/registration.go

This should work across both AzureRM and Azure Stack

Registering Resource Providers using the Profile

---

authentication/auth_method_azure_cli_token.go
authentication/auth_method_client_cert.go
authentication/auth_method_client_secret.go
authentication/auth_method_client_secret_multi_tenant.go
authentication/auth_method_msi.go
authentication/auth_method_msi_test.go
authentication/azure_sp_objectid.go
authentication/builder.go
authentication/config.go

Settled on making in a function call as it's not something most users will be calling, and not frequently at that.

add GetAuthenticatedObjectId call

---

resourceproviders/registration.go

Collect all errors in resource provider registration.
My first go code. So expect go beginners mistakes.
Resolves #45

report all errors in resource providers registration

---

resourcemanager/resourceids/interface.go

This allows these to be located within this package

resourcemanager/resourceids: adding the `Id` interface for Resource Id's

---

resourcemanager/resourceids/ids.go

Original PR https://github.com/terraform-providers/terraform-provider-azurerm/pull/12076

Backport of id.Provider logic

---

resourcemanager/resourceids/ids.go

I was to hasty with https://github.com/hashicorp/go-azure-helpers/pull/79 it seems 😢

Fix: Assign `subscriptionID` with a value

---

lang/pointer/from.go
lang/pointer/to.go
lang/response/response.go
lang/response/response_test.go
resourcemanager/location/normalize_test.go
resourcemanager/tags/flatten.go

Ensuring these are the correct way around

pointer: updating & documenting To* / From* pointer methods

---

resourcemanager/identity/system_and_user_assigned_map.go
resourcemanager/identity/system_or_user_assigned_map.go
resourcemanager/identity/user_assigned_map.go

Spotted whilst patching up https://github.com/hashicorp/terraform-provider-azurerm/pull/14007

identity: fixing a bug where maps were parsed out as lists

---

lang/response/response.go
lang/response/response_test.go

This has come up a number of times, so would be useful to have here

lang/response: adding WasBadRequest

---

resourcemanager/commonschema/identity_system.go
resourcemanager/commonschema/identity_system_or_user.go
resourcemanager/commonschema/identity_system_user.go
resourcemanager/commonschema/identity_user.go
resourcemanager/commonschema/zone.go
resourcemanager/commonschema/zones.go

This PR introduces common Schema for Zones

commonschema: adding SingleZone{Type} and MultipleZones{Type}

---

resourcemanager/zones/expand.go
resourcemanager/zones/flatten.go
resourcemanager/zones/schema.go

I wrote this and thought I committed it to #103 but apparently I reset it 🙃

resourcemanager/zones: reimplementing the Zones package

---

resourcemanager/identity/legacy_system_and_user_assigned_list.go
resourcemanager/identity/legacy_system_and_user_assigned_map.go
resourcemanager/identity/system_and_user_assigned_list.go
resourcemanager/identity/system_and_user_assigned_map.go
resourcemanager/identity/system_or_user_assigned_list.go
resourcemanager/identity/system_or_user_assigned_map.go
resourcemanager/identity/user_assigned_list.go
resourcemanager/identity/user_assigned_map.go

Partially fixes https://github.com/hashicorp/pandora/issues/819

Only add IdentityIds when specified

---

polling/poller.go

Related to https://github.com/hashicorp/pandora/issues/961

Poller: add a new poller with method in constructor and check for 404 responses

---

authentication/auth_method_oidc.go
authentication/auth_method_oidc_test.go
authentication/builder.go

Support generic OIDC auth with ID tokens

---

resourcemanager/commonids/key_vault.go
resourcemanager/commonids/key_vault_key.go
resourcemanager/commonids/key_vault_key_test.go
resourcemanager/commonids/key_vault_test.go

First part of fixing https://github.com/hashicorp/pandora/pull/2181/files

resourcemanager/commonids: adding Common IDs for Key Vault & Key Vault Key

---

resourcemanager/commonids/key_vault.go
resourcemanager/commonids/key_vault_key_test.go
resourcemanager/commonids/key_vault_key_version.go
resourcemanager/commonids/key_vault_key_version_test.go

Fixes https://github.com/hashicorp/pandora/pull/2183/files#r1122986709

resourcemanager/commonids: adding Key Vault Key Version

---

resourcemanager/identity/legacy_system_and_user_assigned_map.go

when generating terrafrom code from pandora, we need this function to transform legacy identity block.

`identity schema`: add expand/flatten from/to model of legacy identity block

---

storage/sas_token.go
storage/sas_token_test.go

Relating to https://github.com/hashicorp/terraform-provider-azurerm/issues/19828

Container SAS token: don't urlencode the `se` and `st` (same as Portal)

---

resourcemanager/commonids/kubernetes_cluster.go
resourcemanager/commonids/kubernetes_cluster_test.go

Related to https://github.com/hashicorp/pandora/pull/2679

commonids: add common id for kubernetes cluster

---

resourcemanager/commonids/managed_disk.go
resourcemanager/commonids/managed_disk_test.go

Removes the churn seen in https://github.com/hashicorp/terraform-provider-azurerm/pull/23233

New Common ID: Managed Disk

---

resourcemanager/commonids/kusto_cluster.go
resourcemanager/commonids/kusto_cluster_test.go
resourcemanager/commonids/kusto_database.go
resourcemanager/commonids/kusto_database_test.go

Reduces external package churn as seen in https://github.com/hashicorp/terraform-provider-azurerm/pull/23381

New Common IDs for Kusto Cluster and Kusto Database

---

resourcemanager/commonids/kubernetes_fleet.go
resourcemanager/commonids/kubernetes_fleet_test.go

Resolves the point 2 review comment in https://github.com/hashicorp/pandora/pull/3416

rename FleetId to KubernetesFleetId
